// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyD-cQznfQBSjyk3BwpawbSNYjtJAY0M9eo',
  appId: '1:468608746624:web:5c8849b6ecd98691895265',
  messagingSenderId: '468608746624',
  projectId: 'skillhub0309',
  authDomain: 'skillhub0309.firebaseapp.com',
  storageBucket: 'skillhub0309.appspot.com', // ✅ FIXED
  measurementId: 'G-7ZD3E7EQ3Y',
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm-nsBCUxREyH-Oe7k4lRLenozUT6RrF4',
    appId: '1:468608746624:android:b98997b05ddb4f25895265',
    messagingSenderId: '468608746624',
    projectId: 'skillhub0309',
    storageBucket: 'skillhub0309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdEwytzRFMrhfQ3AsK5TfAXTZps9mF6U',
    appId: '1:468608746624:ios:3417f112e5e02d02895265',
    messagingSenderId: '468608746624',
    projectId: 'skillhub0309',
    storageBucket: 'skillhub0309.appspot.com', // ✅ FIXED
    iosBundleId: 'com.example.skillhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkdEwytzRFMrhfQ3AsK5TfAXTZps9mF6U',
    appId: '1:468608746624:ios:3417f112e5e02d02895265',
    messagingSenderId: '468608746624',
    projectId: 'skillhub0309',
    storageBucket: 'skillhub0309.appspot.com', // ✅ FIXED
    iosBundleId: 'com.example.skillhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-cQznfQBSjyk3BwpawbSNYjtJAY0M9eo',
    appId: '1:468608746624:web:7b7af07fa54f32c6895265',
    messagingSenderId: '468608746624',
    projectId: 'skillhub0309',
    authDomain: 'skillhub0309.firebaseapp.com',
    storageBucket: 'skillhub0309.appspot.com', // ✅ FIXED
    measurementId: 'G-M7XC81KZLZ',
  );
}